### ISSUE TITLE
Not getting .zip

### ISSUE THREAD

**Issue by Nkaslqi** [EvilBytecode/Batchfile-Token-Grabber-Evilbyte#1]
Hello, why the files don't get zip up? any fix?

**Comment by EvilBytecode** [comment]
Hello! Do you mind contacting me on Discord and/or Telegram? I noticed that there are some bugs and errors that need fixing. No one has reported any issues yet, but you're the first, so I'll jump right into fixing them. I might be able to finish it today, but I'm not sure since I need to visit my girlfriend. It might take some time. Also, please provide features if you have any suggestions. ;px

Discord : bambooware
Discord ID: 1184491148367110184

Telegram  : Bytecode 999

**Comment by EvilBytecode** [comment]
![image](https://github.com/EvilBytecode/Batchfile-Token-Grabber-Evilbyte/assets/151552809/20bcee8e-e56f-4b46-bf3d-feaefc9ea5cd)
Started making some progress 4 you 👍

**Comment by EvilBytecode** [comment]
Hello this will not be updated anymore i decided, making a telegram stealer currently. eductional purpoeses only :P

**Comment by EvilBytecode** [comment]
Hello, contact me back.
